name: Create release

on:
  milestone:
    types: [closed]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-24.04

    steps:
      - name: Get Current Date
        id: get_date
        run: |
          date=$(date +'%Y-%m-%d')
          echo "date=$date" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2.4.0
        with:
          name: ${{ github.event.milestone.title }} (${{ steps.get_date.outputs.date }})
          tag_name: ${{ github.event.milestone.title }}
          generate_release_notes: true
          draft: false
          prerelease: false
          token: ${{ secrets.GHCR_PASSWORD }}